### ISSUE TITLE
[language_request] Add OnlyToday

### ISSUE THREAD

**Issue by molnarmark** [angrykoala/awesome-esolangs#12]
OnlyToday is an esoteric language that works with dates.
The syntax changes based on the date and the hour.

[onlytoday](https://github.com/molnarmark/onlytoday)

**Comment by angrykoala** [comment]
Hi @molnarmark 
Thanks for your contribution. I like the idea of this language very much and it would be great to have it in the list, however, it is still on very early development (which is not a problem) but I have a few concerns:
* Licence is missing, even though you specify it is licensed as MIT in the readme
* More examples are needed (Thats where the fun is), consider adding one or two small examples in the readme as well

Please, take care of these issues before adding the language to the list.

And more of a personal recommendation, try to include more "time" features in your language, eg. the operators or the loops you mention. So it is clear by the code that it will just work once

**Comment by molnarmark** [comment]
@angrykoala Sure. I'm planning on changing around a few of the instructions. Do you mind keeping this open or should I open a new issue when the language is more developed?

**Comment by angrykoala** [comment]
Sure, I'll keep this open, you can comment or directly do a PR whenver you feel the language is mature enough

**Comment by angrykoala** [comment]
Issue closed due to inactivity, please @molnarmark  open a new issue when the language is developed enough to be included in the list
thanks
