### ISSUE TITLE
Add SSSC [language]

### ISSUE THREAD

**Issue by spargle** [angrykoala/awesome-esolangs#64]
[SSSC](https://github.com/spargle/S3C) - This is an Esolang developed by yours truly, @spargle. It's purpose is golfing, and backend microprocessing. (Updated regularly)

**Comment by spargle** [comment]
I will update the link. Should I open a PR, or is it ok if I just leave it as an issue?

-thx

**Comment by spargle** [comment]
[SSSC](https://esolangs.org/S3C_(sssc)) now has a Esolangs.org page!

**Comment by spargle** [comment]
Not trying to be annoying, but is my language going to be added to the list?

**Comment by angrykoala** [comment]
@spargle You can leave it as an issue, but usually it will be way quicker if you create the PR (+ the description by the creator of the language is usually better), by simply creating an issue, you would have to wait until someone takes some time to add it in a PR.

Regarding the language itself, as I see the implementation only consist of 5 commands, 2 of which are requests to an external endpoint. Obviously an esolang doesn't have to be feature complete or have a point, but considering how limited is the language in the current state I'm not sure if it really fits this list at the moment 😞

**Comment by spargle** [comment]
Ok. I am planning to add more features later, and that is when I will open a PR. 

(ps do I have to fork this repo to open a PR?)

**Comment by angrykoala** [comment]
I will close this issue then (you can create the PR without creating an issue when you feel the language is ready)

Yes, you would have to create a fork (it can be deleted once the PR is merged, please refer to [Github docs](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) or Git docs regarding pull requests and merge if you don't know how to do them 

Good luck with your language 👍

**Comment by spargle** [comment]
thx
