### ISSUE TITLE
Add Brainlite

### ISSUE THREAD

**Issue by fsdfdfgdfghSD** [angrykoala/awesome-esolangs#85]
https://github.com/fsdfdfgdfghSD/Brainlite/

**Comment by angrykoala** [comment]
Hi @fsdfdfgdfghSD 
Thanks for your contribution, I like your language, unfortunately, it is a bit too similar to brainfuck (and other brainfuck like languages) for this list (this is not a comprehensive list on languages but a sample of some unique and differents esolangs)

May I recommend you publish this language on https://esolangs.org/wiki/ as esolangs.org is more comprehensive and this seems a fitting addition

Thanks again

**Comment by fsdfdfgdfghSD** [comment]
Alright, thanks for your time.
